### ISSUE TITLE
Error installing .deb package 🐛 

### ISSUE THREAD

**Issue by wesleydmscn** [wesleydmscn/notion-for-linux#2]
### Error log:
```bash
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 5 package 'notion-for-linux:x86_64':
 'x86_64' is not a valid architecture name in 'Architecture' field: character '_' not allowed (only letters, digits and characters '-')

dpkg: error processing archive notion-for-linux_1.0.1_x86_64.deb (--install):
 package architecture (x86_64) does not match system (amd64)

Errors were encountered while processing:
 notion-for-linux_1.0.1_x86_64.deb
```

### To-do
- [ ]  Rebuild with a correct valid architecture name.
- [ ]  Test the new `.deb` file.
- [ ]  Create a new version: `v1.0.2`.
